AWSTemplateFormatVersion: '2010-09-09'
Description: S3 static website (demo). Prefer CloudFront + OAC in production.
Parameters:
  BucketName:
    Type: String
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
Outputs:
  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
